# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "EZProduct"
client_id = "46a6a6c60a57cd723019c930a072aa10"
application_url = "https://ezproduct-app.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_product_listings,read_product_listings"

[auth]
redirect_urls = [
  "https://ezproduct-app.vercel.app/auth/callback",
  "https://ezproduct-app.vercel.app/auth/shopify/callback",
  "https://ezproduct-app.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"
[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
compliance_topics = ["customers/redact", "customers/data_request", "shop/redact"]
uri = "/webhooks"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

